CREATE TABLE todos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  task text NOT NULL,
  is_completed boolean DEFAULT false NOT NULL
);

-- RLS (Row Level Security) を有効化
ALTER TABLE todos ENABLE ROW LEVEL SECURITY;

-- 誰でも（anon key を持つユーザー）がtodosテーブルのデータを閲覧できるようにするポリシー
CREATE POLICY "Public user can view all todos" ON todos
  FOR SELECT USING (true);

-- 誰でも（anon key を持つユーザー）がtodosテーブルにデータを挿入できるようにするポリシー
CREATE POLICY "Public user can insert a new todo" ON todos
  FOR INSERT WITH CHECK (true);

-- 誰でも（anon key を持つユーザー）がtodosテーブルのデータを更新できるようにするポリシー
CREATE POLICY "Public user can update any todo" ON todos
  FOR UPDATE USING (true);

-- 誰でも（anon key を持つユーザー）がtodosテーブルのデータを削除できるようにするポリシー
CREATE POLICY "Public user can delete any todo" ON todos
  FOR DELETE USING (true);